# Generated by Django 4.2.16 on 2024-10-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=50)),
                ('Visa', models.CharField(choices=[('USC', 'US Citizen'), ('GC', 'Green Card'), ('H1B', 'H1B Visa'), ('H4', 'H4-EAD'), ('L2', 'L2-EAD'), ('TN', 'Canadian Visa'), ('OTH', 'Others')], max_length=30)),
                ('Customer', models.CharField(choices=[('HEXA', 'Hexaware'), ('JPMC', 'JP Chase'), ('BOA', 'Bank of America'), ('FAN', 'Fannie Mae'), ('FED', 'Freddie Mac'), ('IQV', 'IQVIA'), ('XLCAT', 'XL-Catlin'), ('AMRI', 'AmeriHealth'), ('EY', 'E&Y'), ('OTHS', 'Others')], max_length=100)),
                ('Poc_Name', models.CharField(max_length=100)),
                ('Req_Name', models.CharField(max_length=15)),
                ('Req_Number', models.CharField(max_length=15)),
                ('Req_Location', models.CharField(max_length=50)),
                ('Pay_Rate', models.FloatField(default=0)),
                ('Bill_Rate', models.FloatField(default=0)),
                ('Margin', models.FloatField(default=0)),
                ('Submitted_Date', models.DateField()),
                ('Status', models.CharField(choices=[('SUB', 'SUBMITTED'), ('L1SEL', 'L1-SELECTED'), ('REJ', 'REJECTED'), ('L1SCH', 'L1-SCHEDULED'), ('L2SCH', 'L2-SCHEDULED'), ('L2SEL', 'L2-SELECTED'), ('OFFER', 'OFFERED'), ('STRT', 'STARTED'), ('L3SCH', 'L3-SCHEDULED'), ('L1REJ', 'L1-REJECTED'), ('L3SEL', 'L3-SELECTED'), ('L2REJ', 'L2-REJECTED')], max_length=20)),
                ('Submitted_By', models.CharField(choices=[('AL', 'ALEX'), ('VK', 'VIKI'), ('SRI', 'SRIVENKAT'), ('OTHS', 'OTHERS')], max_length=20)),
                ('Message', models.TextField(max_length=500)),
            ],
        ),
    ]
