# Generated by Django 4.2.16 on 2024-10-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Req_Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Submitted_By',
            field=models.CharField(choices=[('ALEX', 'AL'), ('VIKI', 'VK'), ('SRIVENKAT', 'SRI'), ('OTHERS', 'OTHRS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Visa',
            field=models.CharField(choices=[('USC', 'US Citizen'), ('GC', 'Green Card'), ('H1B', 'H1B Visa'), ('H4', 'H4-EAD'), ('L2', 'L2-EAD'), ('TN', 'Canadian Visa'), ('OTH', 'OTHERS')], max_length=30),
        ),
    ]
